name: Update Data

on:
  push:
    paths:
      - 'uploads/**'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install openpyxl
      - run: python process.py
      - name: Commit data.json
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add data.json
          git diff --staged --quiet || git commit -m "Veri güncellendi"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
